#!/bin/bash

set -e
root=$(cd "$(dirname "$BASH_SOURCE")/.." && pwd)

main() {
  cd "$root"
  browserify src -o runtime/src.js
  browserify test -o runtime/test.js
  mocha-phantomjs data/test.html
}

main "$@"
