#!/bin/bash

set -e
root=$(cd "$(dirname "$BASH_SOURCE")/.." && pwd)

main() {
    cd "$root"
    mkdir -p coverage
    export PATH="$PWD/node_modules/.bin:$PATH"
    browserify src -t browserify-istanbul -o runtime/src.js
    browserify test -o runtime/test.js
    phantomjs ./node_modules/mocha-phantomjs/lib/mocha-phantomjs.coffee data/test.html spec '{"hooks": "mocha-phantomjs-istanbul", "coverageFile": "coverage/coverage.json", "useColors": true}'
    istanbul report --root . lcov
}

main "$@"
